# Generated by Django 5.2.1 on 2025-06-02 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_heading', models.CharField(default='تیم', max_length=200, verbose_name='عنوان اصلی بخش تیم')),
                ('team_subtitle', models.CharField(default='خوب با تجربه اعضا تیم', max_length=200, verbose_name='زیرعنوان بخش تیم')),
                ('about_text', models.TextField(help_text='متن کامل درباره آژانس/تیم که در صفحه نمایش داده می\u200cشود و قابل اسکرول خواهد بود.', verbose_name='متن توضیحات بخش درباره ما')),
                ('read_more_link', models.URLField(blank=True, help_text='لینک صفحه\u200cای که جزئیات بیشتر در آن قرار دارد (اختیاری).', null=True, verbose_name='لینک بیشتر بخوانید')),
                ('main_image', models.ImageField(blank=True, help_text='تصویر اصلی نمایش داده شده در این بخش (اختیاری).', null=True, upload_to='about_us_images/', verbose_name='تصویر اصلی بخش درباره ما')),
            ],
            options={
                'verbose_name': 'اطلاعات درباره ما',
                'verbose_name_plural': 'اطلاعات درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='شماره تلفن برای تماس مستقیم (اختیاری).', max_length=20, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(help_text='آدرس ایمیل اصلی برای ارتباط.', max_length=254, verbose_name='ایمیل عمومی')),
                ('address', models.CharField(blank=True, help_text='آدرس فیزیکی یا محل کار (اختیاری).', max_length=255, null=True, verbose_name='آدرس')),
                ('linkedin_url', models.URLField(blank=True, help_text='لینک پروفایل لینکدین (اختیاری).', null=True, verbose_name='لینک لینکدین')),
                ('github_url', models.URLField(blank=True, help_text='لینک پروفایل گیت\u200cهاب (اختیاری).', null=True, verbose_name='لینک گیت\u200cهاب')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='نام شخصی که فرم را پر کرده است.', max_length=100, verbose_name='نام فرستنده')),
                ('sender_email', models.EmailField(help_text='آدرس ایمیل شخصی که فرم را پر کرده است.', max_length=255, verbose_name='ایمیل فرستنده')),
                ('subject', models.CharField(blank=True, help_text='موضوع اصلی پیام (اختیاری).', max_length=255, verbose_name='موضوع پیام')),
                ('message_content', models.TextField(help_text='متن کامل پیام یا کامنت.', verbose_name='محتوای پیام')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ارسال')),
                ('is_read', models.BooleanField(default=False, help_text='آیا این پیام توسط مدیر خوانده شده است؟', verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی پورتفولیو')),
                ('slug', models.SlugField(help_text='آدرس URL دوستانه و یکتا (مثال: classic-portfolio)', max_length=100, unique=True, verbose_name='اسلاگ دسته\u200cبندی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پورتفولیو',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پورتفولیو',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('image', models.ImageField(blank=True, help_text='تصویر اصلی مربوط به پروژه را اینجا آپلود کنید.', null=True, upload_to='project_images/', verbose_name='تصویر پروژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('percentage', models.IntegerField(help_text='درصد تسلط به مهارت (عددی بین ۰ تا ۱۰۰)', verbose_name='درصد تسلط')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['-percentage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, help_text='شناسه ویدیوی یوتیوب یا آپارات (مثال: S_CGed6E610) برای نمایش embedded.', max_length=50, null=True, verbose_name='شناسه ویدیو (YouTube/Aparat)')),
                ('title', models.CharField(blank=True, help_text='عنوانی برای نمایش ویدیو (اختیاری).', max_length=255, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, help_text='توضیحات کوتاهی درباره محتوای ویدیو (اختیاری).', verbose_name='توضیحات ویدیو')),
                ('thumbnail', models.ImageField(blank=True, help_text='تصویر کاور یا بندانگشتی برای ویدیو (اختیاری).', null=True, upload_to='video_thumbnails/', verbose_name='تصویر بندانگشتی')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان صفحه پورتفولیو')),
                ('slug', models.SlugField(help_text='آدرس URL دوستانه و یکتا (مثال: two-column-portfolio)', max_length=100, unique=True, verbose_name='اسلاگ صفحه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('custom_url', models.URLField(blank=True, help_text='لینک کامل صفحه پورتفولیو (اختیاری، در صورت خالی بودن از اسلاگ ساخته می\u200cشود).', max_length=255, null=True, verbose_name='آدرس URL سفارشی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Home_app.portfoliocategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'صفحه پورتفولیو',
                'verbose_name_plural': 'صفحات پورتفولیو',
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
