# Generated by Django 5.2.1 on 2025-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='لینک پروفایل اینستگرام (اختیاری).', null=True, verbose_name='لینک اینستگرام'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='لینک پروفایل تلگرام (اختیاری).', null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='watsapp_url',
            field=models.URLField(blank=True, help_text='لینک پروفایل واتس اپ (اختیاری).', null=True, verbose_name='لینک واتس اپ'),
        ),
    ]
