# Generated by Django 5.2.1 on 2025-06-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_contactinfo_instagram_url_contactinfo_telegram_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
