# Generated by Django 5.2.1 on 2025-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', '-percentage', 'name'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='عددی کوچکتر برای نمایش در اولویت بالاتر', verbose_name='ترتیب نمایش'),
        ),
    ]
