# Generated by Django 5.2.1 on 2025-06-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0004_alter_skill_options_skill_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-percentage', 'name'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
    ]
