# Generated by Django 5.2.1 on 2025-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0007_alter_portfoliocategory_options_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The display order for this portfolio item.'),
        ),
    ]
