# Generated by Django 5.2.1 on 2025-06-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0008_alter_portfoliopage_options_portfoliopage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_members/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order for this team member.')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutusinfo',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['order'], 'verbose_name': 'دسته بندی نمونه کار', 'verbose_name_plural': 'دسته بندی های نمونه کار'},
        ),
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'ordering': ['order'], 'verbose_name': 'صفحه نمونه کار', 'verbose_name_plural': 'صفحات نمونه کار'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ویدئو', 'verbose_name_plural': 'ویدئوها'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="مثلاً 'fa-html5' برای آیکون فونت آسوم", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The display order for this category.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
