# Generated by Django 5.2.1 on 2025-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0009_teammember_alter_aboutusinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project'),
        ),
    ]
