# Generated by Django 5.2.1 on 2025-06-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0010_skill_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دسته بندی نمونه کار', 'verbose_name_plural': 'دسته بندی\u200cهای نمونه کار'},
        ),
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'ordering': ['order', 'title'], 'verbose_name': 'صفحه نمونه کار', 'verbose_name_plural': 'صفحات نمونه کار'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-completion_date', 'title'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level', 'name'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title'], 'verbose_name': 'ویدئو', 'verbose_name_plural': 'ویدئوها'},
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='content',
            field=models.TextField(verbose_name='محتوای درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر مربوط به بخش درباره ما (اختیاری)', null=True, upload_to='about_us/', verbose_name='تصویر درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان بخش درباره ما'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش این دسته\u200cبندی را مشخص کنید.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Home_app.portfoliocategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات کامل درباره این نمونه کار (اختیاری)', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='image',
            field=models.ImageField(help_text='تصویر اصلی نمونه کار را آپلود کنید.', upload_to='portfolio/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش این نمونه کار را مشخص کنید.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان نمونه کار'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, help_text='تاریخ تکمیل پروژه (اختیاری)', null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات کامل درباره این پروژه (اختیاری)', null=True, verbose_name='توضیحات پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر مربوط به پروژه (اختیاری)', null=True, upload_to='projects/', verbose_name='تصویر پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان پروژه'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="مثلاً 'fa-html5' برای آیکون فونت آسوم (اختیاری)", max_length=50, null=True, verbose_name='آیکون (Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر مربوط به مهارت (اختیاری)', null=True, upload_to='skills/', verbose_name='تصویر مهارت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0, help_text='سطح مهارت را از ۰ تا ۱۰۰ وارد کنید.', verbose_name='سطح مهارت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مهارت'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='لینک پروفایل فیسبوک (اختیاری)', null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='تصویر عضو تیم را آپلود کنید.', upload_to='team_members/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='لینک پروفایل اینستاگرام (اختیاری)', null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='لینک پروفایل لینکدین (اختیاری)', null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش این عضو تیم را مشخص کنید. اعداد کوچکتر، اولویت بالاتری دارند.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات کامل درباره این ویدئو (اختیاری)', null=True, verbose_name='توضیحات ویدئو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان ویدئو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='فایل ویدئو را آپلود کنید.', null=True, upload_to='videos/', verbose_name='فایل ویدئو'),
        ),
    ]
