# Generated by Django 5.2.1 on 2025-06-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0011_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['order'], 'verbose_name': 'دسته بندی نمونه کار', 'verbose_name_plural': 'دسته بندی های نمونه کار'},
        ),
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'ordering': ['order'], 'verbose_name': 'صفحه نمونه کار', 'verbose_name_plural': 'صفحات نمونه کار'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ویدئو', 'verbose_name_plural': 'ویدئوها'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The display order for this category.'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Home_app.portfoliocategory'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The display order for this portfolio item.'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="مثلاً 'fa-html5' برای آیکون فونت آسوم", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team_members/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The display order for this team member.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
