# Generated by Django 5.2.1 on 2025-06-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0012_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='address',
            new_name='instgram',
        ),
    ]
