# Generated by Django 5.2.1 on 2025-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0013_rename_address_contactinfo_instgram'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='watsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
