# Generated by Django 5.2.1 on 2025-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterField(
            model_name='message',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sub',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
    ]
