# Generated by Django 5.2.1 on 2025-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_alter_message_options_alter_message_fname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیام\u200cهای تماس'},
        ),
        migrations.AlterField(
            model_name='message',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sub',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
    ]
