# Generated by Django 5.2.1 on 2025-06-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='coursera',
        ),
    ]
