# Generated by Django 5.2.1 on 2025-06-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_team', '0002_rename_teammember_coursera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coursera',
            new_name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
