# Generated by Django 5.2.1 on 2025-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_team', '0003_rename_coursera_teammember_alter_teammember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
